name: CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.4
        with: 
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.KEY}}
          port: ${{secrets.PORT}}
          script: |
            CI=true docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
            CI=true docker stop rust-aws-ec2-project1
            CI=true docker rm rust-aws-ec2-project1
            CI=true docker image prune -a -f
            CI=true docker pull rtahiiev/rust-aws-ec2-project1:latest
            CI=true docker run --name=rust-aws-ec2-project1 -d -p 80:8000 rtahiiev/rust-aws-ec2-project1:latest
  